### PR TITLE
[Ready for merging, 1 conflict] Nazi gold: C3

### PR DESCRIPTION
**Pull request by Username-N00b-is-not-available**
As C3 needs more <strike>detail</strike> gold, I <strike>am currently adding</strike> have added it to the maps.

**Status:**

C3M1_A: done (commit a bit later, with C3M1_B)

C3M1_B: done

<details><summary>Screenshot</summary>

Screenshot_Doom_20200328_160009

</details>

C3M2: done, waiting for approval:

<details><summary>Screenshots of most notable gold additions</summary>

Screenshot_Doom_20200327_215014
Screenshot_Doom_20200327_215106
Screenshot_Doom_20200327_215131
Screenshot_Doom_20200327_215213
Screenshot_Doom_20200327_215231
Screenshot_Doom_20200327_215259
Screenshot_Doom_20200327_215312
Screenshot_Doom_20200327_215335
Screenshot_Doom_20200327_214933

</details>

C3M3_A: mostly done. On the third screenshot, you can see an entrance to sewers. As I've done it using a sector portal, there is a possibility to extend the playable sewers area under the town, for example, as the only way to access the church and the cemetery, which could act as optional secret areas. Does this idea have potential?

<details><summary>Screenshots of most notable gold additions</summary>

Screenshot_Doom_20200328_092939
Screenshot_Doom_20200328_092951
Screenshot_Doom_20200328_093031

</details>

C3M3_B: done (just added 21 gold).

C3M4: done, **conflict**

Total gold count in C3M1 through C3M4 (excluding secret maps): **2350**

I'll try to finish this by the end of the week.

### CODE REVIEW

**Comment by Username-N00b-is-not-available** [comment]
Meanwhile, C3M4 is finished. @Tormentor667: there is a conflict in C3M4, could you please apply the changes manually to my version if you did a small amount of fixes in this commit?

I would also like to request adding this image (it can be downscaled) as a painting somewhere in (or near) Rastenburg. For reference, this is from a 1968 Soviet cartoon based on a novel written by [Astrid Lindgren](https://en.wikipedia.org/wiki/Astrid_Lindgren).

<details><summary>Image</summary>

karlson
</details>

BTW, the final battle in Rastenburg needs some ghosts among zombies :-)

**Comment by Tormentor667** [comment]
I can reapply my changes to C3M4 (wasn't much), but I'd suggest you commit your changes until now so others can continue work on the maps you have already done

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667: You mean directly?
Have you checked the additions, are they suitable?

**Comment by Ozymandias81** [comment]
I will cherry pick changes from this PR without merging it using images as rapid reference. Next time if you plan a map addition better do that directly, you are on team for reasons N00b (my phone refuses to tag you)

**Comment by Ozymandias81** [comment]
Cherry picking now.

**Comment by Ozymandias81** [comment]
Merged already so no need to merge this too, and about C3M3_A keep in mind that portals decrease map performance.

**Comment by Ozymandias81** [comment]
Working on C3M4, fixed some stuff and added Astrid image

**Comment by Tormentor667** [comment]
@Username-N00b-is-not-available  - Generally you can commit your changes, explain what you've done so I can check them. If it isn't fitting, I can adjust it or revert the commit :)

**Pull request closed without merging**
