### PR TITLE
Attempt to make spotlight visibility work better

### PR DESCRIPTION
**Pull request by Talon1024**
Rework spotlight visibility calculations to use Level.SphericalCoords instead of the ugly old manual calculations. From the little testing I've done on a small test map I made, it seems to work well. What do you think @AFADoomer?

### CODE REVIEW

**Comment by Talon1024** [comment]
In case you're wondering why I did this: On C2M1, in the courtyard with the two spotlights, you can walk into the middle of the courtyard and get spotted, even if you're not being lit up by the spotlights. The spotlights don't even shine on the middle of the courtyard.

**Comment by Talon1024** [comment]
Here's the reference for Level.SphericalCoords: https://github.com/coelckers/gzdoom/pull/553

**Review by AFADoomer — APPROVED** [review]
Looks good, and seems to match original behavior in basic testing...  Updates of obsolete code are always good!

**Comment by Tormentor667** [comment]
Very good! Thanks for that @Talon1024

**Pull request merged**
