### PR TITLE
Prevent flinch when player has less than 1 health

### PR DESCRIPTION
**Pull request by yqco**
This is to fix a bug where the flinch script was interfering with the death roll.

### CODE REVIEW

**Comment by Ozymandias81** [comment]
Brilliant! Thanks yqco! Also check the Intromap, we added you on credits slideshow inside Scripts! :muscle: 

What we need now is to fix inheritances with the [LowHealth](https://github.com/Realm667/WolfenDoom/blob/master/source/boalib.acs#L600) script then I guess eveything will be done (maybe we'll think if we must disable the flinch while underwater, but this is just my idea).

**Comment by yqco** [comment]
That's awesome; thank you.

I can add a way for the flinch script to be disabled/enabled on a per-player basis, if you think that would be useful. The flinch mechanic could also be tied to a convar if it's decided to be a player option.

Regarding the [LowHealth](https://github.com/Realm667/WolfenDoom/blob/master/source/boalib.acs#L600) script, I'm not sure what you mean by inheritances. Is the issue that the red screen pulses ([M_INJ](https://github.com/Realm667/WolfenDoom/blob/master/graphics/hud/general/M_INJ.png)) are not occurring below 30 health?

**Comment by Ozymandias81** [comment]
Yes, sorry for not being "polite" concerning terms, but that's exactly the issue: the red screen won't pulses anymore, and also we can't hear the heartbeat and related stuff.

Concerning the convar tweak well, atm it's a no because it would break the gameplay difficulty imho... and now that I think I am not exactly sure of the "disable flinch underwater" thing, we just have to fight with sharks and a couple of "ship" enemies on c1m2, so... Maybe it's pointless for now.

**Comment by yqco** [comment]
I've made a [pull request](https://github.com/Realm667/WolfenDoom/pull/23) to address the issue. The heartbeat sound should be louder and the screen should start pulsing at and below 30 health.

**Pull request merged**
