### PR TITLE
New replacement for threefiv font

### PR DESCRIPTION
**Pull request by Talon1024**
This is a new replacement for the threefiv font. It's monospaced, larger, more detailed, and supports all of the necessary characters. However, [this bug](https://forum.zdoom.org/viewtopic.php?f=2&t=72478) should be fixed first, since the extra spacing looks ugly.

### CODE REVIEW

**Comment by AFADoomer** [comment]
This does bad things at lower or scaled resolutions (vid_scalefactor below 1.0).  The characters become completely illegible.

**Comment by Ozymandias81** [comment]
Any news regarding this one?

**Comment by Tormentor667** [comment]
Is this a dead end now?

**Comment by Tormentor667** [comment]
@Talon1024 so, will this be added or not?

**Comment by Talon1024** [comment]
If the Russian and/or Czech players feel the extra diacritics are necessary, I'd like to add it. There's also the fact that some of the Cyrillic characters in the current threefiv font are much wider than the others, which probably looks ugly.

**Comment by AFADoomer** [comment]
This is also not a 1:1 replacement for the existing font, and will require additional work...  

Spacing is problematic, and the scaling doesn't match the current font.

Updating the font.inf file to:
```
CellSize 5, 10
Kerning -1
Scale 1.5
```
makes things fit far better, but if I also add `FontHeight 6` to make the line height match, I get garbled text.

**Comment by Tormentor667** [comment]
Well, if it is a back step I would rather not add and merge it.

**Comment by Talon1024** [comment]
> This is also not a 1:1 replacement for the existing font, and will require additional work...
> 
> Spacing is problematic, and the scaling doesn't match the current font.
> 
> Updating the font.inf file to:
> 
> ```
> CellSize 5, 10
> Kerning -1
> Scale 1.5
> ```
> 
> makes things fit far better, but if I also add `FontHeight 6` to make the line height match, I get garbled text.
> 
> EDIT: And the issue with lower/scaled resolutions is still there, regardless - the text is illegible at low resolutions.

I can fix the issue with the font height by converting the font into a "variable-width font" (Splitting the font character sheets into individual characters and adding offsets to the characters with diacritics). I decided to make the font that tall so that there is enough space above and below the "base characters" for the diacritics.

**Comment by MuadDib90** [comment]
I can help here, if I know what to do.

If you ask me, I think the best solution could be the base for characters a bit larger. Now it is 5 width and 8 height. The new could be like 7 to 10 maybe?; so the characters expecially with diacritics (height) and cyrillic characters (width) can be fit at all.  Then there should not be such problem(s), right?

I am ready to add new characters or repair the present ones (as I did with some when adding czech diacritics)...

**Comment by MuadDib90** [comment]
After this commit above 6b4005a is there anything I can do to help?
The issue seems to be stuck at some point... (to me at least)

**Comment by Talon1024** [comment]
I'll get right back to it as soon as I find out how to make ImageMagick automatically remove blank rows/columns from images. There are A LOT of them, after all.

**Comment by AFADoomer** [comment]
I don't have a problem adding this if we also keep the old THREEFIV as a fallback for users who use vid_scalefactor values less than 1.0...  I'll have to do some code for the status bar/widgets and the achievement menu, but those are the only places THREEFIV is used, I think.

**Comment by Ozymandias81** [comment]
So I have merged MuadDib90 work a while ago... what should I do with this one then?

**Comment by Talon1024** [comment]
I'll merge it myself

**Pull request merged**
