### PR TITLE
Reimported script [nuked the other fork and started clean]

### PR DESCRIPTION
**Pull request by SibTiger**
Updated the foundation of the shell script, _Zip.bat.  The user can now
select three options as to how to compile the project:
* Default build
* Use the original properties as before
* Best compression
* Archive the project, but use the best compression possible.
* No compression
* Archive the project, but do not compress the data within the archive
file.

This script still needs additional work, but it is stable as it
currently stands.

### CODE REVIEW

**Comment by Ozymandias81** [comment]
Thanks a lot SibTiger! I'll merge this immediately :muscle:

**Comment by SibTiger** [comment]
Going from the [previous conversation](https://github.com/Realm667/WolfenDoom/pull/30#issuecomment-238126229), would you like me to create the exclusion list next or should I just focus on generalized improvements in the script?

**Comment by Ozymandias81** [comment]
First exclusion then improvements I guess. Thanks.

**Comment by SibTiger** [comment]
Okay, I wanted to make sure - I was under the impression that you might be working on it.  I'll try to get on that later tonight or before I sleep.

**Pull request merged**
