### PR TITLE
Pain overlay shader

### PR DESCRIPTION
**Pull request by AFADoomer**
Added a shader-based pain overlay that causes the player's view to fade all colors to red but still maintain contrast.

This is set up to only affect damage types that are set to have an alpha of zero in the player class.  This is to avoid conflicting with hard-coded screen handling for poison fades.

Needs to be reviewed and tested.

### CODE REVIEW

**Comment by Tormentor667** [comment]
Sorry for the question but how can I test this without merging the pull request? Just found out that I never did that before.

**Comment by Talon1024** [comment]
You can checkout the "PainShader" branch to test this pull request without merging it.

**Comment by Tormentor667** [comment]
Thank you I will try that

**Comment by Tormentor667** [comment]
Tried it but somehow doesn't work for me
grafik

**Pull request merged**
