### PR TITLE
Use GHOST flag on SharkBlocker

### PR DESCRIPTION
**Pull request by Talon1024**
I added the GHOST flag to the SharkBlocker, and the THRUGHOST flag to projectiles that I think should be able to fire into the water.

### CODE REVIEW

**Comment by Ozymandias81** [comment]
Thanks Talon! It fixed the issue, there are still a couple of weapons to fix but I can do that (grenades and astrorocket mainly)! Thanks a lot!

**Comment by Talon1024** [comment]
Actually, I set the +THRUGHOST flag on AstroRocket, but it still seems to bounce off of the water. I have no idea what is going on. Maybe a bug?

On the other hand, throwing grenades into the water seems to work fine for me.

**Comment by Ozymandias81** [comment]
Uhm yes, I noticed that yesterday as well the changes on grenades, but if you try to throw them exactly in front of you, for example inside the pool on Testmap, there will be a 90% quite of probabilities that the grenade will bounce straight instead going down...

Concerning the AstroRocket well... I tried to add -CANBOUNCEWATER and didn't work... Do we need to add a bounce state and change in some ways behavior to fix the thing? [USEBOUNCESTATE](http://zdoom.org/wiki/Actor_flags#Bouncing)

**Comment by Tormentor667** [comment]
Thanks alot Talon!

**Comment by Ozymandias81** [comment]
Torm, JFYI, it seems that the bounce issue with Grenades and AstroRocket could be addressed as a [Z/GZDoom internal bug](http://forum.zdoom.org/viewtopic.php?f=2&t=47853)... Uhm... Well, we don't have so many situations with a grenade by hand and a pool, except on map c1m0, c1m2 and c1m6 afaik...

**Pull request merged**
