### PR TITLE
- add a gldefs generator tool that scans textures for materials and c…

### PR DESCRIPTION
**Pull request by madame-rachelle**
…reates a GLDEFS file based on what it finds for each texture. See https://forum.zdoom.org/viewtopic.php?p=1122102#p1122102 for usage. Windows/Wine only

### CODE REVIEW

**Comment by Ozymandias81** [comment]
Thanks @madame-rachelle , gonna merge this and we'll see if we gonna add displacement materials yet, maybe that shader on the zdoom forums post is still not fully mature... Wonder if that would be possible to have it switchable for users, with a zscriptified condition or something like that. Because atm on my end is a no for this, unless we'll go for a separate .pk3 for this feature.

First image, C1M1 start without displacement, 75fps
Screenshot_Doom_20191018_004549

Second image, C1M1 start with displacement, 48fps
Screenshot_Doom_20191018_004700

**Comment by Tormentor667** [comment]
Found a bug with the created .txt file:

```
material texture "textures/AFRK_T02.jpg"
{
	shader "shaders/displacement.fp"
	texture displacement "materials\displacement\AFRK_T02.png"
}
```

...results in a bug. All "\" should be "/"

**Comment by Tormentor667** [comment]
Another problem: Two textures that have a filename that's too long for shortnames turn into an issue when starting GZDoom with results like this:

`material texture "DOOR_B20"
{
	shader "shaders/displacement.fp"
	texture displacement "materials/displacement/DOOR_B20R_OPEN.png"
}`

`material texture "DOOR_B20"
{
	shader "shaders/displacement.fp"
	texture displacement "materials/displacement/DOOR_B20Y.png"
}`

I think the script needs a special case where textures that have longer filenames than 8 characters automatically only generate longname variants (in GZDoombuilder, they always get used as longnames anyway if they are longer than 8 characters).

Otherwise GZDoom bombs out.

**Comment by madame-rachelle** [comment]
Ooof okay, I will work on these.

**Comment by madame-rachelle** [comment]
> 
> 
> Thanks kindly Rachael, this works like a charm :) One question though: We have some subdirectories in the /textures/ folder, e.g. /aztec/, /astrostein/ and so on. Currently if we place a displacement map into the displacment material folder, the script doesn't know if the original texture is in the /textures/ folder or in a subdirectory of the folder, what breaks the functionality for long-texture-names. Can something be done about that?

Can you clarify this? I am kind of confused what you mean, here. I have it scanning the entire textures/ folder and subfolders using a simple "dir /a /s /b folder\\*" and piping that command to a "for" statement. It then takes only the names of the files and searches them for their displacements in the materials/displacements folder and if it finds one it will create a definition for it.

> I think the script needs a special case where textures that have longer filenames than 8 characters automatically only generate longname variants (in GZDoombuilder, they always get used as longnames anyway if they are longer than 8 characters).

Done

> ...results in a bug. All "" should be "/"

Fixed

**Comment by Tormentor667** [comment]
Thanks for the fixes and improvements, works already much better now. Regarding the "subdirectory" thing, maybe you have already taken care of that and I just don't know yet as I haven't tried it yet :)

In the root directory you find a "/textures/" folder with various subfolders, for example "/textures/astro" for Astrostein textures. 

If I create a displacement map for the texture "/textures/astro/ASTR_BBX.png", the cmd line tool you've create will first make the following SHORTNAME code (in case "/materials/displacement/ASTR_BBX.png" is there):

`material texture "ASTR_BBX"
{
	shader "shaders/displacement.fp"
	texture displacement "materials/displacement/ASTR_BBX.png"
}`

but will it, when it creates the LONGNAME code, also incorporate the subfolder of the actual texture just like this:

`material texture "textures/astro/ASTR_BBX.png"
{
	shader "shaders/displacement.fp"
	texture displacement "materials/displacement/ASTR_BBX.png"
}`

or will it make the LONGNAME "textures/ASTR_BBX.png" as it assumes, the main texture is in the "textures" folder?

Thanks for clarifying :)

**Comment by madame-rachelle** [comment]
When using displacements it will always use the full (not short) name of the texture, without the path. So for example if you had "/textures/doors/big_massive_nazi_door.png", and "/materials/displacement/big_massive_nazi_door.png" - it would reference that.

The tool no longer creates short names for textures whose filenames exceed 8 characters. So in this case, either the displacement for the original texture name is there, or it's not.

**Comment by Tormentor667** [comment]
I think that answers my question :) Thanks kindly, already working with the tool and it does its job now :)

**Pull request merged**
