### PR TITLE
My changes to C1M2

### PR DESCRIPTION
**Pull request by Talon1024**
I made these changes:
- added doors to the electric chair chamber.
- added a switch on the back of the electric chair that opens the prison gate doors to the room where James Ryan is being held.

I've been working on this for a while, and there's more things to come.

### CODE REVIEW

**Comment by Ozymandias81** [comment]
Ok while actually is really late where I live (2am), I am quite sure that your changes here are very useful _(just reading comments, didn't test anything for now)_... especially the fix for grenades on Intermap imho. Anyway here comes the problems:

1. DoomJuan is in the way to improve map c1m2 and he has several ideas on going too, but some stuff needs to be fixed really, like polyobjects + interrogation room
2. There it seems to be some conflicts due to [my previous fixes concerning map c1m2](https://github.com/Realm667/WolfenDoom/commit/4192d3947a09ca179efb3f5339c8f7ff8a4b5a88) and, I assume, the skybox itself
3. I can only test this commit but can't add it until Tormentor _(on vacancy until next week afaik)_ or DoomJuan will read this pull in order to give you a reply or clues for fixes _(I can do that too, but I don't know exactly what's up with DoomJuan idea, I only know that it's very good and he also wants to keep the Shooting Range place but somewhere near the end of the map)_

Don't worry I'll inform them of this pull request, you did a very good job even if I didn't test it though so you'll deserve a proper reply.

**Comment by Ozymandias81** [comment]
Uhm well I tested the Intermap and grenade fix doesn't seem to work as intended: I bought 2 grenades from the shop then started the training... I know what's up: there is a script that remove all things from our inventory before we start such training (the CLEAR INVENTORY script).
Anyway this thing must be addressed though, it's pretty important for make things coherent and obvious.

**Comment by Ozymandias81** [comment]
Concerning map c1m2 I have some issues there:

1. If I merge this pull request, I have to get [a big amount of files re-merged](https://github.com/Realm667/WolfenDoom/pull/15/commits/02d72f2038cfb5f6984ff520548bf1ace6e45dad) and I don't feel really comfortable with it, even if it's just a branch thing
2. DoomJuan is working on it and we must coordinate our work, but it's hard from you because we mainly discuss from facebook... would you like to join us on our private chat then?
3. Could you please close this pull request  and open a new one with only the updated map though? And if you go for the Intermap then work on the latest updated one. I need a polish pull request in order to keep things as clear as possible, I hope you can do that.

So for now I'll commit your modified version of c1m2 + some adjustments done by me then you have to continue your work over it then.

**Comment by Talon1024** [comment]
I lost my changes to the Intermap, including the grenade fix, when I made the "[Merge master branch](https://github.com/Realm667/WolfenDoom/pull/15/commits/02d72f2038cfb5f6984ff520548bf1ace6e45dad)" commit.

**Comment by Ozymandias81** [comment]
So [this one](https://github.com/Realm667/WolfenDoom/pull/15/commits/a7305a956c7586c6c03f9422259d6215275e2d3f) wasn't the last update though?

**Comment by Talon1024** [comment]
As I said, I merged my branch with the WolfenDoom master branch, and as a result, lost my changes to Intermap.

> Merge master branch.
>
> This unfortunately undoes a lot of my work, but oh well.

**Comment by Ozymandias81** [comment]
Alright then.
So is it possible for you to continue your work over my changes?
Anyway we have another problem there: you and DoomJuan must coordinate your works together in order to not mess up things I guess.

**Comment by Talon1024** [comment]
Yeah. I'll see if I can re-do my changes to the Intermap ACS as well.

**Comment by Ozymandias81** [comment]
Thanks and don't forget to work over the updated Intermap obviously :tongue:

**Pull request closed without merging**
