### PR TITLE
Improved handling with git feature check

### PR DESCRIPTION
**Pull request by SibTiger**
Improved the handling to support checking of the .git directory within the source code.  If the .git directory does not exist within the source code (for whatever reason), then the git features is disabled regardless if git executable was detected.  This will avoid posssible errors from occurring if the .git directory was not reachable.

### CODE REVIEW

**Comment by Ozymandias81** [comment]
Thanks Tiger, you roar! :smile:

**Comment by Ozymandias81** [comment]
Uhm what could be [this thing](http://forum.zdoom.org/viewtopic.php?f=19&t=47801&start=1545#p939510)? Is it right what GENTEK suggested though? Could be there a way to trick that then?

**Comment by SibTiger** [comment]
No, 7zip is not required to be in the system's %PATH%.  It looks like the path's matches but the program is unable to find anything within the /Tools/ directory, which is what the program utilizes to invoke 7zip  and the exclusion lists.

I am going to investigate this and see what /could/ be the problem here...

**Comment by SibTiger** [comment]
Downloaded the source directly throw GitHub's website service and extracted the archive data file using 7zip aswell as Windows Zip (embedded in Windows), nothing out of the ordinary other than Windows Protection confirming if I want to run the script (part of Windows 8+).  So, downloading the source from GitHub's website service doesn't cause any issues here.  Maybe it's internal - within the program, I'll take a gander.

**Comment by SibTiger** [comment]
This snippet: `IF NOT EXIST "%ProgramDirPath%tools\7za.exe"`  seems to hold just fine.  I also invoked the program where the client and program path's differ, yet - everything is working just fine.

Maybe its a problem with permissions, assuming NTFS is being used here?  I'll play around with the permissions and maybe get somewhere?
If all else fails, I ponder if Jimp has a bad download or something is wrong with the console from Jimp's end that I can not control.

**Comment by SibTiger** [comment]
With altering permissions I was able to reproduce the message exactly, which was expected.  I have two things in which I would need Jimp to perform before I come to my conclusion, I'll need to see the `tree` of the directory hierarchy, and an MD5 checksum of the archive file that Jimp downloaded from the GitHub webservices.  I'll provide Jimp the information once I find a safe MD5 program....

**Comment by SibTiger** [comment]
> Turns out that a USB Bluetooth adaptor I had plugged in was the source of the problem. And the only way I was able to find out that info was because of Gentek's picture instructions.[[1](http://forum.zdoom.org/viewtopic.php?p=939549#p939549)]

Well, I guess that's good.  Though I don't understand how that could be so, there's not enough information.
If this issue comes up again, I already have a [script ready](https://gist.github.com/SibTiger/4c06e9e4791ba01df284f240ad7bd75e).

**Comment by Ozymandias81** [comment]
Yeah it seems to be a weird issue, never had such one on my side... Keep in contact with Jimp as a suggestion, for now I think this small issue is just a minor nitpick.

Concerning the MD5 check... Gosh, still need to test it properly, but in the end I think this one will be needed only if we'll go through releases... If I understand correctly :tongue:

**Comment by SibTiger** [comment]
> but in the end I think this one will be needed only if we'll go through releases... If I understand correctly 

Yes, its good practice but not mandatory.  However, I wanted to compare the hash that Jimp has with my hash.  If there was any missing files within the archive or something was corrupted, the hash would let me know as the hash's would be completely different.

I'll keep the script around if incase someone hits the issue again.  It's only necessary for diagnostics to figure out the problem, but shouldn't be used as part of the project.

**Comment by SibTiger** [comment]
Just an FYI, I have officially retired the script 'IntegrityChecker.bat'.  Since the main launch, I don't think anyone has reached any problems with the compiler.  I am not exactly sure if the verbose error update ever helped out or not, but no one else has came forward with issues since.  But, again, you can reach me if something goes horribly wrong or needing changes.

Congrats on the Chapter 1 release!

**Comment by Ozymandias81** [comment]
Thank you very much Tiger!
And yes it seems that nobody there has get some issues concerning the compiling batch process, probably because you nailed it totally!
Anyway I noticed that it is always better to compile the .pk3 without any compression method at all, but it's just a thing on very low-end profile rigs afaik (it is the way I compile it before I go for tests and my pc sucks a lot, you now... :smile: )...
Beside all, thank you again Tiger! Feel free to come with feedbacks on ZDForums, Doomworld, Realm667 or ModDB if you like, that would be very appreciated from you!

**Pull request merged**
