### PR TITLE
Highlight archive datafile in new window

### PR DESCRIPTION
**Pull request by SibTiger**
Once a new archive file has been generated, highlight the file in a new window.  This should be easier for users to identify where the file is located and to easily access it without confusion.

### CODE REVIEW

**Comment by SibTiger** [comment]
If there is any issues or ideas anyone has for this compiler, please let me know before I break it and implement Git support.

Thanks in advanced

**Comment by Ozymandias81** [comment]
What do you mean exactly with "Git support"? I am not technically so skilled when it comes this kind of things :sos: 
I mean, isn't it a batch file? What's the plan? :grey_question: 

BTW this new add-on makes even a chipmunk to understand the "what's going on?" :smile: 

Thanks!

**Comment by SibTiger** [comment]
> What do you mean exactly with "Git support"? I am not technically so skilled when it comes this kind of things 🆘 

As of right now, the batch file is unable to retrieve the commit hash ID and is incapable of updating the localised repository.  In order for this shell script (or batch script) to perform these actions, I will need to find a way for this script to try to detect the 'Git.exe' that the user has installed and perform the mentioned actions.  For example, this [script](https://github.com/Realm667/WolfenDoom/blob/master/build.sh#L7) is capable of updating and using the date of the latest commit.  I've highlighted line 7, but there is also line 3 and 4.  Another example, is [TGRDM3's compiler](https://github.com/SibTiger/TGRDM3/blob/master/Tools/Compiler%20%5BBootless%20Star%5D/scripts/CompileProject_GitControl.bat) - which is essentially what I am going to utilize.

However, to make all this work and minimize interactions as much as possible - is what I am not exactly sure about.

> I mean, isn't it a batch file? What's the plan? ❔ 

What I have in mind:
* Use git to update the local repo, focus only on the master branch.
* Fetch the latest local commit hash ID and attach the ID to the archive file name.  For example: `wolf_boa.pk3` will become `wolf_boa-`[8a0070c](https://github.com/Realm667/WolfenDoom/commit/8a0070cb71293e26c3c65fa007644fb9931874c0)`.pk3`.  Doing this, will allow multiple versions of the project depending on the latest commits from the user's local repo.

However, this will only be possible if the shell script is able to find the git executable.  If the script is unable to find the git executable, then the feature will not work but everything will be the same as it is right now.

If you guys have any other ideas or suggestions, feel free to let me know - I'll try to make something happen.  If incase you guys don't really want this support, I could make one adjust instead.  The adjustment I would like to include will involve deleting the archive file with the same name, which this will delete the old archive file and allow a new and updated archive file to take its place.

> BTW this new add-on makes even a chipmunk to understand the "what's going on?" 😄 

Hopefully these improvements will be easier for everyone ☺️

**Comment by Ozymandias81** [comment]
This .git thing sounds pretty fine imho, but only if it won't cause you headaches and loads of hours lost on it :tongue: 
Concerning "The Search for the Git.exe" (sounds like a Threepwood adventure), [I wonder if this would be of some help for the purpose](http://stackoverflow.com/questions/1437457/how-do-i-find-full-path-to-an-application-in-a-batch-script)...
Hopefully you'll sort that hash ID too, can't track something useful for you atm.

BTW I use GitHUB Desktop portable, which I got obviously once I created my profile here on GitHUB... I noticed that paths are created with random names, I think this could be a problem in order to get the Git.exe.
FYI I use Win7 32bit Ultimate sp1 and this is how my GitHUB folder "structure" (don't know if the term fits good here, but it's like with cats: If I fit, I sit :laughing: 
git

In the end, feel free to come with something, I appreciate really this idea. :muscle: 
The only rule here would be that even dumb users (and those ones without github installed) can build the .pk3 and play BoA, but I perfectly know that you know it and that's the main purpose of this build.bat file.

May the Schwartz be with You, always.

**Comment by SibTiger** [comment]
> Concerning "The Search for the Git.exe" (sounds like a Threepwood adventure), I wonder if this would be of some help for the purpose...

The best I can do is check if its in %PATH% and check some common places, if all of that fails - then there's nothing more I can do.  The search tactic used in the link is not really ideal for this sort of program for a few reasons:
 1. It can presumably take too much time to start up the program and have it run a brute force scan for anything that has "git.exe".
 2. If git.exe was found during the brute force scan, is it truly the git program that we want or is it some other program that has no relation to git - that we want?

It's too much of a gamble if it 'works', but a lot of users - myself included - will not like latency or be bothered for an optional feature.  Best example to illustrate my point, Windows 7 Aero glass theme - periodically at the night hours Windows 7 will run the Windows Experience Index and check if the computer can still handle Aero's glass theme and whatnot.  As I am a night person, this 'feature' always drived me through the roof as it hogged the CPU and GPU resources for ~5 minutes.  Thus anything that I was doing - is on hold until Windows 7 finally finished with that annoying test.  To relate that example with this program, no matter what I do - at every startup or first-startup (if we use a save config), the user has to wait - and wait.  The program's latency should never be ridiculous, $microSeconds <= 500.000ms is suitable and tolerable for everyone.

> Hopefully you'll sort that hash ID too, can't track something useful for you atm.

No worries, I've already accomplished this in [TGRDM3's compiler](https://github.com/SibTiger/TGRDM3/blob/master/Tools/Compiler%20%5BBootless%20Star%5D/scripts/CompileProject_GitControl.bat#L64).  I'll just use that exact statement in the _WolfenDoom_ build script, of course I'll have to migrate it a bit 😉 .

> BTW I use GitHUB Desktop portable, which I got obviously once I created my profile here on GitHUB... I noticed that paths are created with random names, I think this could be a problem in order to get the Git.exe.

Do you know if its registered in %PATH%?  To check this, go to `CMD.exe` and type: `ECHO %PATH%`, visually scan for anything that resembles `git` or `git.exe`.  If its not there, you could also check: `SET` and visually scan for anything that resembles `git`.

> The only rule here would be that even dumb users (and those ones without github installed) can build the .pk3 and play BoA, but I perfectly know that you know it and that's the main purpose of this build.bat file.

Hopefully the improvements thus far helps in that area; I am afraid that with more expansion giving - it'll get harder as more options will need to be added in as I have to think - what would this team and general end-users need this script for and what must it accomplish along with different scenarios.  For one, with having git supported, when you guys plan for a release or public builds - you may not want any git hash ID in the archive name, but in testing you would possibly want that feature.  However, as the script gets bigger the more it turns off users - no matter what.  The CUI is simply to intimidating for a lot of users and they may not bother with using it, no matter how easy it is and hold the user's hand.  I think I hit that issue hard in [Bootless Star](https://github.com/SibTiger/BootlessStar)....

If you have any default suggestions (not\or configurable), we can discuss it further.  For example:
 * Should we always try to sync the local repo to the master repo?
 * Should we always attach the latest local commit hash to the archive file name?
 * Should we even bother with fetch commit changelogs?
 * Should we make using git features as an option
 * Should anything be toggable; such as don't sync the repos but attach the commit hash to file name?

If we do focus on configurable settings, I would request that a personalized .bat file that contains the users preference should be in .\Tools\ directory and is ignored with git - as its just a personalized file from the end-user.

> May the Schwartz be with You, always.
Now that I think about it, this project is seriously lacking [merchandising](https://youtu.be/fgRFQJCHcPw)!

**Comment by Ozymandias81** [comment]
While the PATH and SET thing didn't show me what I needed, because my Git is installed on my User profile folder, atm I don't have suggestions for you concerning "default" stuff... probably only the "git features as an option" must be a thing on my side, but I'll come with proper suggestions later...

PS: Unfortunately I can't see those videos because they are restricted on my country :anger: , but I perfectly know which were them :smile:

**Comment by SibTiger** [comment]
* If you were to try to invoke `git` in cmd, do you get an error message?  I created a [small script](https://gist.github.com/SibTiger/9dc96a262bd72de0ce7b79aa514cfc77#file-findgit-bat) to help you with this, can you tell me the output that you get?
* What type of client do you use?

I am going to try to investigate what options are available if nothing works for you.

**Comment by Ozymandias81** [comment]
This is what I exactly get...
image

...and with your small script run from C:\...
image

My portable installation was the same I downloaded the 1st time I had to register on GitHUB, which I've got from [here](https://github.com/integrations/github-desktop) afaik...

...and this is my version installed actually...
image

...which stays on my pc under my personal Profile folder (C:\:Users\...)

Obviously with `git` from cmd prompt doesn't happen anything.

**Comment by SibTiger** [comment]
Thanks, this is enough information to work on.  With everyone else on the team, do they have the **EXACT** same setup as yourself?  If not, - I guess I'll need to know if there setup as well.

Since you have GitHub for Windows and its in your main HDD, I think there might exist an easy solution - which you'll have to edit %PATH%.  I can walk you through this personally via Skype or Google Hangouts.  But before we go this route, I first want to check if there's any other option.  I'll get back to you guys soon.

**Comment by Ozymandias81** [comment]
I am sorry but for personal reasons I don't chat via Skype or Google Hangouts... if you like you can join our facebook supersecret Team Chat... just search for my profile under Blade of Agony website.
This way you'll know exactly if all other team members will have my settings for Github, which I really doubt :smile: 

BTW I don't feel safe with all that stuff on my previous comment, so... can you copy for yourself that somewhere so I can get rid of that comment from here? Thanks, I'll wait for your reply.

**Comment by SibTiger** [comment]
> I am sorry but for personal reasons I don't chat via Skype or Google Hangouts... if you like you can join our facebook supersecret Team Chat... just search for my profile under Blade of Agony website.

I'll look into that depending on what I find with the GitHub for Windows client.

> BTW I don't feel safe with all that stuff on my previous comment, so... can you copy for yourself that somewhere so I can get rid of that comment from here? Thanks, I'll wait for your reply.

Done

**Comment by Ozymandias81** [comment]
Thanks SibTiger :muscle:

**Comment by SibTiger** [comment]
Just so everyone knows, I am kinda swamped with assignments and other large tasks.  I'll try to make tiny implementations when I can....

**Comment by Ozymandias81** [comment]
No worries SibTiger, I am in the way to take a small break because I need it after 2 years of modding...
I'll get back on BoA mainly this weekend, hopefully if my pc won't act crazy for its last time...

**Comment by SibTiger** [comment]
> My portable installation was the same I downloaded the 1st time I had to register on GitHUB, which I've got from here afaik...

When you ran the script I [provided](https://gist.github.com/SibTiger/9dc96a262bd72de0ce7b79aa514cfc77#file-findgit-bat), was the _GitHub for Windows_ also running?

**Comment by Ozymandias81** [comment]
Sorry I have some problems with my pc and didn't had the opportunity to test it properly... :sob:

**Comment by SibTiger** [comment]
Sorry to hear.

I did some quick research on how I can be able to accommodate your scenario.  Thus far, you'll have to edit your `$PATH`.  There is some _quick and dirty_ methods, however - for prolong _stability_ - its not feasible to support it as the environment could change over time.

When your PC is back up and running again, here is some help to accomplish getting git.exe to work within the environment.
* [Adding Git to Path when using _GitHub for Windows_](http://www.chambaud.com/2013/07/08/adding-git-to-path-when-using-github-for-windows/)

However, instead of using `C:\Users\SomeUserName\AppData\Local`, I would suggest using `%LocalAppData% instead.  Doing this, you'll be sure that: if incase you change your username, change the name of your home directory, or even relocate the entire LocalAppData region, that variable should still be up-to-date and requiring no attention.

**Example use of the variable:**
`[Thu.01.Sep.2016 11:58:51.60] [C:\Users\Nicholas]`
`$ echo %LocalAppData%`
`C:\Users\Nicholas\AppData\Local`

**Comment by SibTiger** [comment]
I am going to try to focus on fully implementing the Git support; the next pull request should fully support and work with git in an [OOBE](https://en.wikipedia.org/wiki/Out-of-box_experience) environment.

I am hoping it only take an hour or two in development time to fully integrate the features....

**Comment by Ozymandias81** [comment]
Thanks Tiger, I'll check these things when I'll be in the mood to test stuff... Actually I am really worried of my PC health but this will be sure the first thing to do. Meanwhile I'll try to merge updates from you from time to time while I am able (my PC likes to turn off  suddenly).

**Comment by SibTiger** [comment]
Is it Windows that shutsdown unexpectedly or hardware?  Assuming hardware, sounds like the PSU is going south or the system board is dying, I doubt any modern CPU's today automatically forcefully shutsdown PC if the TJ max was hit.  Best advice I have is to open up the system and remove any dust (if any) and inspect the PSU and system board.  If the PSU is faulty or is the source of problems, don't use it again as it can't damage any hardware components also connected to it.

**Comment by Ozymandias81** [comment]
Thanks Tiger, btw it's the hardware itself... but it seems I've managed to take care another time this issue: the Power button seems to be the culprit, which it ad red/black cables very near together... For now it seems to be good, I just have a small issue with an old hdd but it happens only if I reboot (hangs on BIOS then tell me to add proper boot device then restart, but still have to test with my recent fixes anyway).
It's very hard and boring to explain, but I perfectly know how to check my PC, but surely it got several ESD back in the years... Well I have this PC and I can't get a new one, so I'll do the best to keep it alive as until its last day.

**Comment by SibTiger** [comment]
>  but I perfectly know how to check my PC

I do apologize; you didn't ask for my help - but I pre-emptively offered anyways 😜.


Glad that you got your stuff working though - and at the best time [too](http://forum.drdteam.org/viewtopic.php?p=60289#p60289)!

**Comment by Ozymandias81** [comment]
I also apologize if it sounded a bit harsh on my side, usually I don't write / say things like that but when it comes a different language than our "mother" one, well it's time for some misunderstanding :tongue: 
BTW I really appreciate your help instead, but as of now the problem needs to be physically checked, so it's hard to fix it via suggestions in any case...
It's like one month that I need to force the power process on my PC, like pressing the Power button different times in sequence (yeah, it's totally weird I know) until both OS hdd and dvd starts.... After this strange "sequence", I have to cross my fingers and to hope that my PC remain :on: 

Concerning GZDoom releases, I really can't wait for this SSAO feature and the enhanced dynlight system calculation, which if it will happen as it is meant to be, we'll get Skyrim on GZDoom directly! :laughing: 

Sorry for my bad english, it's very late here (I think it's the same for you, I am italian) but hopefully with a fresh mind I'll get rid of these issues on my PC in a snap-time :smile: 

Thanks another time for your suggestion, I also have a friend that said the same thing but fortunately I did them before. Good night! :night_with_stars:

**Comment by SibTiger** [comment]
I can't wait for the new version also, it's going to be amazing!

**Comment by Ozymandias81** [comment]
Definitely indeed! I wonder how dpJudas will solve the LinePortal issue and the skybox rendering too, it seems that he is in the way to apply an alpha channel over places where GZDoom must exclude the SSAO effect... amazing stuff!

**Pull request merged**
