### PR TITLE
NPC addition to C3M5_A (incomplete)

### PR DESCRIPTION
**Pull request by Username-N00b-is-not-available**
Added a Wehrmacht soldier who hides in the sewers of the initial area of C3M5_A. The very first secret (with MP 40) on this map now has a switch behind the moving stone, which must be activated before it reaches the wall. The switch opens a grate in the tunnels, which is now a polyobject instead of a linedef. The new passage at (-18112, -12608, -200) leads to a dead end with a broken door, near which there is the new NPC. If talked to, before the last dialogue page he gives the player a dummy token; this token is only used once in a script for a door near (-13640, 10448, -8). It can be opened for supplies (possible design inconsistencies here).
Bugs: the name of NPC and his sprite are not shown, yet they do already exist in the repo. The conversation mugshots do not exist yet. The secret works as I intended though.

### CODE REVIEW

**Comment by Tormentor667** [comment]
I think reaching the switch before the polyobject blocks the switch is nearly impossible. It's a non-intuitive mechanic that has never been used before and you have no idea that something like this is hinted at. I doubt that anyone without that knowledge will find the switch.

Regarding the proceeding secret locations, can you provide screenshots? I don't seem to be able to get what has been planned atm.

**Comment by Tormentor667** [comment]
I think reaching the switch before the polyobject blocks the switch is nearly impossible. It's a non-intuitive mechanic that has never been used before and you have no idea that something like this is hinted at. I doubt that anyone without that knowledge will find the switch.

Regarding the proceeding secret locations, can you provide screenshots? I don't seem to be able to get what has been planned atm.

**Comment by Username-N00b-is-not-available** [comment]
I thought such a mechanic was OK for a penultimate level... though it is really non-intuitive, I agree. Might just have placed a small switch on the back wall; I'll think about it some more.
Doom Builder locations:
udb
In-game screenshots:
Screenshot_Doom_20200120_095243
Screenshot_Doom_20200120_095301
Screenshot_Doom_20200120_095312
Screenshot_Doom_20200120_095432
Screenshot_Doom_20200120_095502
Screenshot_Doom_20200120_095508
Screenshot_Doom_20200120_095528
Screenshot_Doom_20200120_095535
What am I doing wrong with the sprite? Why does it not show up..? I placed it into an appropriate directory; and UDB actually displays it, but the game doesn't! The new actor has two frames, not one, so it cannot be that infamous issue...
Also, the skill names which I added in previous commit somehow got corrupted (?) and show only the last three skills' names. The first two are shown as 'BOASKILL1' and 'BOASKILL2', though in MAPINFO the respective names are specified with a dollar...

**Comment by Ozymandias81** [comment]
You need to apply [offsets](https://forum.zdoom.org/viewtopic.php?f=39&t=56521) to sprites to make them show up in game.

**Comment by Username-N00b-is-not-available** [comment]
Totally forgot about it, thank you! I just copied and pasted parts of the sprite, the offsets probably got zeroed while resizing the image.

**Comment by Tormentor667** [comment]
Gonna merge the pull request and do some fine-tuning - good additions :) Your help is appreciated!

**Comment by Username-N00b-is-not-available** [comment]
Yeah, feels good to hear that! Thank you.
Probably the secret area needs some redesigning, though :-)

**Comment by Tormentor667** [comment]
Well, feel free to come up with similar little additions on the other chapters, nice touches!

**Comment by Ozymandias81** [comment]
Don't forget to update your work since I have nitpicked your stuff with this [commit](https://github.com/Realm667/WolfenDoom/commit/e712a707a89794f8f5376cc3f94a8e14e160d130)

**Pull request merged**
