### PR TITLE
Make treasure chests more generic

### PR DESCRIPTION
**Pull request by yqco**
- Treasure chests don't require an action special anymore.
- The empty chest and reward pickup now share the TID of the locked chest, allowing any to be referenced by scripts.
- Treasure chests can now specify an optional script number to execute when they are opened.
- Treasure chests can now specify an optional objective index to clear when they are opened.

### CODE REVIEW

**Comment by yqco** [comment]
This pull request will break the treasure chests in existing maps. I've put together another [pull request](https://github.com/Realm667/WolfenDoom/pull/33) to fix the existing maps if this request is merged.

**Comment by Ozymandias81** [comment]
So if it will be accepted I'll just need to merge the last pull request or both?

**Comment by yqco** [comment]
If you just accept this one, the treasure chests in the existing maps will be broken until mappers can fix them. It's a simple fix.

The other pull request includes the map fixes.

**Comment by yqco** [comment]
Here's a demo map that illustrates working treasure maps, in case this patch gets merged but the map fix one doesn't. [wolfendoom_chests_test.zip](https://github.com/Realm667/WolfenDoom/files/399110/wolfendoom_chests_test.zip)

**Comment by Ozymandias81** [comment]
Right, so I'll merge both then.

**Comment by Ozymandias81** [comment]
I'll check later this evening np.

**Comment by Ozymandias81** [comment]
Consider this merged. I'll check it properly later.

**Pull request merged**
