### PR TITLE
Add zsh build script for Unix platforms

### PR DESCRIPTION
**Pull request by Talon1024**
This is a slightly modified version of my personal build script.

### CODE REVIEW

**Comment by Ozymandias81** [comment]
Thanks a lot Talon1024, consider this merged immediately. :+1:

**Comment by Ozymandias81** [comment]
BTW I suggest to update the builder with proper exclusions following those ones present on the [batch file](https://github.com/Realm667/WolfenDoom/commit/f8fea19c278b068ddb32a46341f74537594c9e6e#diff-ccd701d3fe134c26b974350c7ffe833eR118) for windows

**Comment by Talon1024** [comment]
The exclusions seem to work fine for me. The double asterisk is a [recursive glob](http://unix.stackexchange.com/questions/49913/recursive-glob).

**Comment by Ozymandias81** [comment]
Well, if it works for you then... :tongue: 
Surely you don't have all those backup# files inside maps or .db thumbnails, but those are there just for developers and not for "guests", so you are totally right actually with the "work fine to me".
Because the batch file is built taking in consideration ALL exclusions we need to take care in order to test properly BoA outside GZDoom Builder (which is drastically fundamental for testing scripts).

**Comment by Talon1024** [comment]
Well, I work with SLADE on Linux, so I don't have .db thumbnails or Doom Builder backup files.

**Comment by SibTiger** [comment]
The exclusion wont be so much of a big deal if a list is going to be used.  The list can be used on both scripts - which will be easier for everyone and less redundancy on code changes within the scripts.

**Comment by SibTiger** [comment]
Is it possible that you can add in the new exclusion file list?

Files that contain a list:
* [7zExcludeListDir](https://github.com/Realm667/WolfenDoom/blob/master/tools/7zExcludeListDir.txt)
  * This list contains directories from the root of the WD
* [7zExcludeList](https://github.com/Realm667/WolfenDoom/blob/master/tools/7zExcludeList.txt)
  * This list contains individual files from within the entire project

Example:
[`-x@"./tools/7zExcludeListDir.txt" -xr@"./tools/7zExcludeList.txt"`](https://github.com/Realm667/WolfenDoom/blob/master/_zip.bat#L118)

**Comment by Talon1024** [comment]
I just made a new pull request to make my build script use the same exclusion lists as yours.

**Pull request merged**
