### PR TITLE
Recompressed PNGs

### PR DESCRIPTION
**Pull request by Kroc**
Ran all the PNGs through PNGGauntlet and shaved about 13 MB off. Approx
2hrs @ 4GHz for anybody wanting to try this at home. Lossless JPG
optimisation will save another 3 MB, but that will come later as I need
to correct edge cases in my scripts.

### CODE REVIEW

**Comment by Ozymandias81** [comment]
Welcome Kroc :+1: 
I see you used a very good method but I must ask to you first: did you test all of them, did you check alpha channels and background color though? For the moment I don't merge this because these are a lot of changes, let's see what others will think.

**Comment by Tormentor667** [comment]
Thanks for the pull request Kroc, but can you check if all the textures still work as intended before committing this change? For instance sensible textures are those with alpha channels or transparency.

**Comment by Kroc** [comment]
I pushed this late last night, so it is untested; I'm compiling a new pk3 right now (=294.6 MB) however I'm not sure how I would test _all_ the textures as I would have to play everything and look everywhere. My suggestion is to merge it and if we notice any broken textures they can be individually reverted using git.

Whilst PNGGauntlent's tools are lossless _visually_ (any image that has 256-colours or less will be converted to an 8-bit PNG) such that no pixels will be different from before but the internal encoding may be vastly different. It is plausible that gzdoom might choke on these esoteric PNG formats.

On a side note, whilst 13 MB might not be all that much in the grand-scheme of things, I'm hoping that less data = less first-frame lag from texture pre-caching. I'm working on some batch scripts to automate compressing of PNGs/JPGs which could one-day become part of the compiler. Since I only have integrated graphics and primarily play on a netbook (though I have an i7 4970 desktop for number-crunching) I'm also experimenting with making an automated "mini-me" version of the game with larger textures halved in size and everything reduced to 256-colours per texture using pngquant and the like.

**Comment by Kroc** [comment]
Okay, problem, NPC sprites are not appearing at all!

**Comment by Ozymandias81** [comment]
I suggest to not go for massively optimization of files or things like that, we know what we are doing and this was one of the first thing [we did back in the days](https://github.com/Realm667/WolfenDoom/commit/0b6647f4755102a6c6a6fd2e7bc900ecf2422209)...
Also you must take in consideration that some stuff present on BoA uses Doom palette + GZDoom doesn't recognize all kinds of image compression.
In the end if we go for brute force shrunk on PNG textures, we'll experience severe slowdowns on old machines even if we set GL precaching to true.
We are optimizing textures mostly on and off and that's something I and Tormentor we can take care via automated Slade plugins or Photoshop.
So please test your pull requests next time in order to not flood the list in the future, also to save you a lot of trashed free time like in this peculiar case :tongue: 
Thanks anyway for your effort!

**Comment by Kroc** [comment]
I would be glad to file a bug with gzdoom if I could narrow down the PNG format that's causing the problem. I've no experience with doom mapping, so if either of you could throw together a single-room WAD with a few NPCs idling around in it I would do the work of finding what PNG feature is causing the fault. Running PNG optimisation on their resources is something all kinds of mappers might do occasionally and they shouldn't have to suffer missing graphics due to particular edge cases.

**Comment by Ozymandias81** [comment]
You can only shrink graphics for GZDoom by choosing among 2 types of compression methods: PNGCrush or PNGOut.
Instead when you go for a brute shrunk method, which usually impliese the usage of both forementioned methods, PNG graphics will lose:

1. Transparency
2. Original background color
3. Quality
4. Embedded offsets

Point 4 is what happened to your shrunked sprites, so this would mean that in-game you can't see any sprites because they've lost their necessary alignment needed to work properly while in game, unless you define them HAND BY HAND through [TEXTURES](http://zdoom.org/wiki/TEXTURES) lump. Only a couple of sprites on BoA, mainly weapons (kicks if i recall correctly, also it's used for BJ crouch sprites though) use such feature because it would imply an humongous amount of work to do that.

**Comment by Kroc** [comment]
Aha! Point 4 makes perfect sense. I've writing a batch script to do recompression more intelligently rather than 'drop everything into PNGGauntlet' so I can quite easily modify that to keep embedded data. A bit of tuning should solve this problem. Thanks very much for the direction!

**Comment by Ozymandias81** [comment]
> You can only shrink graphics for GZDoom by choosing among 2 types of compression methods: PNGCrush or PNGOut.

Trust me, you can't do nothing more than that in the end.
Actually we use the Crush method through Slade automated process
image
.

**Comment by Gaerzi** [comment]
SLADE's optimize PNG feature is intended to preserve non-standard chunks used by ZDoom (of which the offsets are the most important); most PNG optimization tools will just remove them. In fact, the way SLADE's feature works, it just keeps them in memory, run the PNGs through the external programs, and then puts the chunks back in.

Some PNGs might lose their alpha channels when an optimizer figures that they have few enough unique colors that they can transform the sprite from RGBA to paletted. SLADE does not check for this situation, however.

Opaque textures should however be a good test case. If PNGGauntlet can make them smaller than PNGOUT/PNGCrush, then I could add PNGGauntlet to the list of PNG optimizers one might want to use from within SLADE 3. Keep in mind that I recommend to use _either_ PNGOUT _or_ PNGCrush, not both at once. DeflOpt you can pretty much always use, but it only shaves off a few bytes per file.


Lastly: PNGs are always PNGs, there's no such thing as "esoteric PNG compression". It's not like the ZIP format, even though you can use different approaches to get the best compression, they're always decompressed the same way. E.g. and to simplify, the sequence 123412341234343434 can be compressed either as "1234"x3+"34"x3 or as "1234"x2+"12"+"34"x4, one of these choices gives a better compression than the other, but if you can decompress one you can also decompress the other.

**Comment by Ozymandias81** [comment]
Thanks for clarifications Gez :sweat_smile:

**Comment by Kroc** [comment]
Whilst specificities could be overcome (you can control exactly which PNG chunks are included/excluded via the command line), I'll be getting into the realm of diminishing returns. As only a correction, I haven't said "esoteric PNG *compression*", but "esoteric PNG *formats*" -- that is, 1/2/4-bit PNGs with colour, 24-bit PNGs with 1-bit alpha and so forth.

**Comment by Ozymandias81** [comment]
I wonder if GZDoom will interprete correctly such kind of formats but I say let's see :thinking:

**Pull request closed without merging**
