### PR TITLE
C1M5: More polishing.

### PR DESCRIPTION
**Pull request by Talon1024**
Fix alignment of underwater crate textures.
Added more detail to the sewer right before the exit.
Fixed the ladders going into/out of the initial sewer area.
Moved player start position back to its normal spot.
Fixed the swinging door leading into/out of the salon where you meet Juliette.
Fixed missing textures in the visible/playable part of "Le Juif et la France".
Fixed offsets of the flats on the boxes at the start of the level.

### CODE REVIEW

**Comment by Ozymandias81** [comment]
Thanks for these fixes Talon :+1:

**Comment by Talon1024** [comment]
You're welcome.

Can you please check your PMs on ZDoom forums? I have an important message for you and Torm.

**Comment by Ozymandias81** [comment]
I checked but I must see what Torm thinks first. It's 5am here and the same is for Torm, so I think you'll need to wait some hours for the answer.

**Comment by Ozymandias81** [comment]
Ok I must say a thing concerning changes to map Talon: while we aren't in touch with you unless from GitHub, it's hard to work in a synched way because we can't discuss properly concerning changes... and I must say that DoomJuan didn't like yours because he had something different in mind, but he also doesn't disagree and helping hand on mapping (specially script-wise things too).

This is what DoomJuan said actually, and I think he is totally right:
"I'd rather, in future, you not upload anything he does if I am working on something and to tell him not to touch maps that either me or Dan are working on, and if he does want to contribute he will have to join us on Facebook team chat because we have a good work dynamic here and it cannot be altered for someone who just pops in now and then to add minor adjustments"

So do you want to join us on FB chat? Thanks anyway for your work.

**Comment by Talon1024** [comment]
Well, at the time I made my changes, I noticed a significant lack of activity, so I thought "why not?". For example, [there was a 5 day margin](https://github.com/Realm667/WolfenDoom/commits/master/maps/C1M5.wad) from DoomJuan's last commit to C1M5 to my first commit in my previous pull request.

I also mistakenly believed Blade of Agony was releasing on August 1, so I thought I had to get C1M5 polished or else it would be released in an unfinished state.

That said, I am interested in joining the Facebook chat.

**Comment by Ozymandias81** [comment]
Alright then, just check my name from Google (sorry to say that but I don't want to kill my privacy lol), you can get it from the [BoA webpage](http://boa.realm667.com/index.php/team).
After that, send me a request for friendship then I'll add you in. :+1:

**Pull request merged**
