### PR TITLE
Display error if bad input

### PR DESCRIPTION
**Pull request by SibTiger**
If the user inputs something other than the supported values from the Main Menu, display an error message notifying them that the input was invalid.

### CODE REVIEW

**Comment by Ozymandias81** [comment]
Thanks, merged. :muscle:

**Comment by SibTiger** [comment]
The next update I am going to focus on providing better error detection on the required dependencies and possibly add in a few small features while I am at it.  I don't know how long it'll take for the next update to be ready.

**Comment by Ozymandias81** [comment]
Don't worry, take your time. No need to hurry.
This new compiler is awesome if compared to the old one, I really like how it's going with the user-friendly thing.
I must say another time: thanks a lot Tiger!

**Comment by SibTiger** [comment]
My pleasure, I am really happy that you guys like the improvements :)

**Pull request merged**
