### PR TITLE
Add more info to appdata

### PR DESCRIPTION
**Pull request by Alexander-Wilms**
This changes the ID to use underscores instead of dashes, since IPC on Linux requires that there's no dashes in application/package IDs (cf. https://github.com/flathub/flathub/pull/248). Switching to underscores avoids naming inconsistencies, even if it's not required.

I also added a `<releases/>` section. Optionally, each release can have its own

```
      <description>
​        <p>Fixes issues X, Y and Z</p>
​      </description>
```
section.

Finally, this adds an [OARS](https://hughsie.github.io/oars/) age rating section, which was created by @fishxz.

I made two commits, since git didn't recognize that the .appdata.xml was renamed and that spaces were changed to tabs at the same time.

### CODE REVIEW

**Comment by Talon1024** [comment]
I don't think the OARS section is very accurate. Here's my take on it. I explain my reasoning below, although there are spoilers.
`xml
  <content_rating type="oars-1.1">
    <content_attribute id="violence-cartoon">none</content_attribute>
    <content_attribute id="violence-fantasy">intense</content_attribute>
    <content_attribute id="violence-realistic">intense</content_attribute>
    <content_attribute id="violence-bloodshed">moderate</content_attribute>
    <content_attribute id="violence-sexual">none</content_attribute>
    <content_attribute id="violence-desecration">intense</content_attribute>
    <content_attribute id="violence-slavery">intense</content_attribute>
    <content_attribute id="violence-worship">none</content_attribute>
    <content_attribute id="drugs-alcohol">moderate</content_attribute>
    <content_attribute id="drugs-narcotics">none</content_attribute>
    <content_attribute id="drugs-tobacco">moderate</content_attribute>
    <content_attribute id="sex-nudity">mild</content_attribute>
    <content_attribute id="sex-themes">none</content_attribute>
    <content_attribute id="sex-homosexuality">none</content_attribute>
    <content_attribute id="sex-prostitution">none</content_attribute>
    <content_attribute id="sex-adultery">none</content_attribute>
    <content_attribute id="sex-appearance">intense</content_attribute>
    <content_attribute id="language-profanity">moderate</content_attribute>
    <content_attribute id="language-humor">moderate</content_attribute>
    <content_attribute id="language-discrimination">intense</content_attribute>
    <content_attribute id="social-chat">none</content_attribute>
    <content_attribute id="social-info">none</content_attribute>
    <content_attribute id="social-audio">none</content_attribute>
    <content_attribute id="social-location">none</content_attribute>
    <content_attribute id="social-contacts">none</content_attribute>
    <content_attribute id="money-purchasing">none</content_attribute>
    <content_attribute id="money-gambling">none</content_attribute>
  </content_rating>
`

Fantasy violence: At the end of C2M6_C, the player has to fight the Angel of Death before getting his hands on the titular weapon. The player also fights ghosts, undead monks, giant spiders, rats, and bats.
Realistic violence: Most of the enemies are either humans, robots, dogs, or small creatures. Human enemies can be set on fire with the flamethrower (Pyrolight/Flammenwerfer), or gibbed with grenades. Enemies bleed when shot.

**Comment by Alexander-Wilms** [comment]
Thanks for the detailed ratings. I haven't completed the game yet, so I only skimmed over your reasoning. Should I use your XML in the PR, and or squash the commits? Or I could skip them and you add them separately.

**Comment by Talon1024** [comment]
I think I'll add my ratings separately.

**Comment by Alexander-Wilms** [comment]
Thanks!

**Pull request merged**
