### PR TITLE
Infinite ammo, AstroLuger

### PR DESCRIPTION
**Pull request by Username-N00b-is-not-available**
Added TIF_NOTAKEINFINITE to weapons which did not have it.

The plasma pistol sprites look like a placeholder IMO, will these graphics for Astro Luger be better? (source taken from https://forum.zdoom.org/viewtopic.php?f=43&t=52164&start=1275)

### CODE REVIEW

**Comment by Ozymandias81** [comment]
Sorry but we used Astrostein weapons in line with "old mac sprites" format, so I can't merge this until you'll remove the sprites. It looks too "modern" too compared to other weapons

**Comment by Tormentor667** [comment]
I agree with you, Ozy

**Comment by Username-N00b-is-not-available** [comment]
I just thought that the pistol sprites differ in style from other Astrostein weapons the most. I do not insist on replacing them, though.
What about the infinite ammo cheat?

**Comment by Tormentor667** [comment]
The cheat thing is fine :)

**Comment by Ozymandias81** [comment]
Well I am going to merge the commit and then revert changes to sprites then :)

**Comment by Tormentor667** [comment]
💪🏻

**Comment by Username-N00b-is-not-available** [comment]
@Ozymandias81, you manually reverted the sprite changes after merging the PR. I've heard that there is some mechanism (cherry-picking?) that allows to apply an arbitrary part of the changes instead of the full difference. Does it work for individual files, or only for commits? If yes, maybe it is just less convenient to use than undo the changes by hand? Would like to know more about this.

**Comment by Ozymandias81** [comment]
Well, while I have never used the cherry-pick method since I am more familiar with mine, you can use the Shell to cherry-pick a branch and merge items from it onto another (usually master), but I don't fie the method very intuitive so I prefer my way. More info can be found [here](https://stackoverflow.com/questions/9339429/what-does-cherry-picking-a-commit-with-git-mean)

**Pull request merged**
