### PR TITLE
[Minor] Spell Check

### PR DESCRIPTION
**Pull request by SibTiger**
Changed: Insufficent => insufficient

### CODE REVIEW

**Comment by Ozymandias81** [comment]
Hi Tiger,

do you know what's going on [here](https://forum.zdoom.org/viewtopic.php?f=19&t=47801&start=1815#p978666)? Thanks in any case :smiley:

**Comment by SibTiger** [comment]
Hallo,

Are you able to reproduce the issue as well?  If you are able too, what kind of shell are you using (PowerShell, Command) and how are you executing the program (step-by-step)?  If this issue becomes a known issue, a work-around would be to use the *nix script by Talon1024, as Bash is now possible in Windows 10.

I will personally check the script when I possibly can, I am presently over flooded with Matrix Algebra, Data Structures, and Database & Design assignments, so it may take me some time to check and debug the program myself.

**Comment by Ozymandias81** [comment]
Hello Tiger!

Well unfortunately I can't reproduce that issue, never had a single one with your compiler I must say.
All I do is right-clicking the .bat from my own repository and then run it... At least it doesn't pass from the github step, you know (update the .pk3 following the commit number etc.)
And nothing strange happen as well if I download BoA as a .zip from github (unzip the .zip then run the compiler).

No problem if you are flooded with math stuff (so much stuff I see :open_mouth: ), this isn't a priority and at least only one user had such issue it seems.

Thank you Tiger for the support and GodSpeed! :muscle:

**Comment by SibTiger** [comment]
@Ozymandias81 && @Tormentor667 

Hallo,

   How is the compiler working out for you guys?  Is there any issues or maybe a feature that you guys need that will help out your development or end-users abroad?  Feel free to let me know 😉 

regards,

**Comment by Ozymandias81** [comment]
Hi Tiger, such a long time!

Well atm it works perfectly on my side, no problems or any kind of glitches (I am now on Win7 64bit YAY, and I'll switch to a 6core cpu before this summer finally!)
There was a plan to keep the Lowres folder for sprites, but judging by the amount of work DoomJedi and myself are doing with sprites... well we thought that this is a bit unfair and non-sense (had to work both Hires/Lowres folder once an actor was going to be added - argh)
For the rest I think we'll need something different for the compiler then you'll surely be informed by one of us.

Thank you Tiger!

**Comment by SibTiger** [comment]
Great!  Rock solid program 😉 

I know this isn't my project but throwing my 2-cents in anyways, as for the SPRITEs, it would be best to keep one set to unify the project settings and offer the same gaming experience to everyone - equally.  I don't think there would be any real benefit for keeping low and high resolution SPRITEs concurrently other than more bloat and higher work-loads to keep both sets in the project.  Infact, I highly doubt there is any true performance difference - other than image size.  HOWEVER, if it was Voxels, 3D Models vs. SPRITEs, then everything changes dramatically.  Luckily, that doesn't seem to be in question here.  Otherwise, yes, you are right that the work load is unfair and it seems it would be for a less to no gain.

If you guys need anything with the program, feel free to let me know and I'll try to get it in for you guys - when I have the time to do so 😉

**Pull request merged**
