### PR TITLE
Optimize images using `oxipng -o6 --strip --zopfli`

### PR DESCRIPTION
**Pull request by Calinou**
According to [#TODO.txt](https://github.com/Realm667/WolfenDoom/blob/9cee5aa55ebbf6b0ce23c365470da6982aa55860/%23TODO.txt#L4), some images should be optimized further. So there it is; I left [oxipng](https://github.com/shssoichiro/oxipng) running for about 3 hours in its highest (yet still lossless) optimization settings :slightly_smiling_face:

This will increase Git history size for sure, but it could also make the final PK3 smaller, which benefits end users.

### CODE REVIEW

**Comment by Ozymandias81** [comment]
Well, thank you a lot for invest so much with these optimizations, but we have some problems here unfortuantely:

- As a pull request, this is to much extent since it replaces a huge amount of files
- Everything that has been optimized, specially graphics, textures and sprites with alpha channel needs playtesting and this would require an astonishing amount of time
- Since idk how this OxiPNG works, I wonder if its way to optimize graphics may haul old GPUs somehow
- The method I actually use via Slade is through PNGCrush plugin and DeflOpt, and afaik it works in every circumstances so this is tested on my end
- Best way to do these kind of massive optimizations is always before an official release or day by day / file per file, but everything needs to be tested first

So I highly appreciate your job done here, but atm I don't feel confident to merge this pull since too many things have been changed and not being 100% aware of them makes me decide to not merge this for now.

**Comment by Calinou** [comment]
> Everything that has been optimized, specially graphics, textures and sprites with alpha channel needs playtesting and this would require an astonishing amount of time

I agree this could be an issue if some features rely on the color of fully transparent pixels (which is stripped by default). If this is an issue, I could run it again with this optimization disabled.

**Comment by Ozymandias81** [comment]
Yeah transparency is fundamental, mainly on sprites but also on several textures and graphics as well. So I suggest to correct and come with a similar pull request but once only we'll be near release time, which should happen at the end of this year probably

**Comment by Calinou** [comment]
@Ozymandias81 That makes sense. Should I leave it open and amend it before release, or close it and reopen another one when a release is due?

**Comment by Ozymandias81** [comment]
Better close this and make a new one in the future. Thanks again for your efforts :)

**Comment by mgrinzPlayer** [comment]
Hi, I analyzed oxipng source code (main.rs and lib.rs) files.

From help and after reading source code (because 'help' is out of date):
```
Optimization levels:
    -o 0  =>  --zc 3 --nz                  (0 or 1 trials + 1 alpha trial)
    -o 1  =>  --zc 9                       (1 trial, determined heuristically + 1 alpha trial)
    -o 2  =>  --zc 9 --zs 0-3 -f 0,5       (8 trials + 1 alpha trial)
    -o 3  =>  --zc 9 --zs 0-3 -f 0-5       (24 trials + 1 alpha trial)
    -o 4  =>  --zc 9 --zs 0-3 -f 0-5 -a    (24 trials + 6 alpha trials)
    -o 5  =>  --zc 3-9 --zs 0-3 -f 0-5 -a  (168 trials + 6 alpha trials)
    -o 6  =>  --zc 1-9 --zs 0-3 -f 0-5 -a  (216 trials + 6 alpha trials)
```
When using Zopfli algorithm, it becomes:
```
Optimization levels:
    -o 0  =>  --nz       (0 or 1 trials + 1 alpha trial)
    -o 1  =>             (1 trial, determined heuristically + 1 alpha trial)
    -o 2  =>  -f 0,5     (2 trials + 1 alpha trial)
    -o 3  =>  -f 0-5     (6 trials + 1 alpha trial)
    -o 4  =>  -f 0-5 -a  (6 trials + 6 alpha trials)
    -o 5  =>  -f 0-5 -a  (6 trials + 6 alpha trials)
    -o 6  =>  -f 0-5 -a  (6 trials + 6 alpha trials)
```
There's no difference among -o4, -o5 and -o6 presets for Zopfli algo. If we ignore alpha trials, -o3 is also the same.

By default oxipng performs some reductions: palette reduction, bit depth reduction, color type reduction and alpha reductions. As you wrote: "transparency is fundamental" for WolfenDoom - Blade of Agony. I checked all "alpha reduction" related things in oxipng source code.

There are 6 alpha reductions:
- "alpha_to_black" - always enabled
- "alpha_to_white", "alpha_to_up", "alpha_to_down", "alpha_to_left", "alpha_to_right" - enabled for -o4 and above.

We can not disable that "alpha_to_black", we have to remove it from source code and compile custom binary. Which I've done some time ago. I moved some lines from one place to another.... After patching oxipng, -o3 does only 6 trials without alpha reduction. I also added few switches to skip image processing when "width is bigger than X" and "height is bigger than X", because I have an old Intel i3-4160, I wanted to try on smaller PNG files first.


Here are my steps:
- I downloaded WolfenDoom zipped source code, commit a22c61fb0391875313b2745a27fa72d3052a79c5
- extracted only png files ( 7za x WolfenDoom.zip *.png -r )
- there were 17881 png files, which is about 248 MiB (260'756'906 bytes)

- I optimized small png files with my modified oxipng binary. (log file for statistics):
oxipng.exe --max-width 512 --max-height 512 -r -o 3 --zopfli --strip all | tee -a log.log

- oxipng only does palette, bit depth and color type reduction.

statistics:
- 225 skipped files (width bigger than 512 or height bigger than 512)
- 498 files - Zopfli algo can not optimize it better (size has slightly increased). Oxipng doesn't overwrite original file if it fail to optimize it.
- 261 files - size not changed
- 16897 optimized files - average is 20.01% less
- total size: 230 MiB (241'619'333 bytes), 18MiB less

- made some tests: I used build.bat to create wolf_boa.pk3 and gzdoom dev build Aug 01 2019 11:14:20 (gzdoom-x64-g4.2pre-312-g154af34cd.7z)

Conclusions:
Looks like gzdoom or "WolfenDoom - Blade of Agony" still doesn't like some optimized PNGs. NPCs disappeared, some objects are mispositioned.
I don't know which reduction cause this: "palette reduction", "bit depth reduction" or "color type reduction". Or maybe oxipng bug or bug in package used by oxipng.




Few days later I optimized the rest, those 225 files. I was just curios about overall savings.

FINAL statistics:
- 498 files - Zopfli algo can not optimize it better (size has slightly increased). Oxipng doesn't overwrite original file if it fail to optimize it.
- 263 files - size not changed
- 17120 optimized files - average is 19.93% less
- total size: 222 MiB (233'030'772 bytes), 26MiB less

If anyone interested, here are zipped PNGs (17120 optimized, 263 optimized but same size, 498 intact)

pngfiles_a22c61fb0391875313b2745a27fa72d3052a79c5.zip:
https://mega.nz/#!ZEUSgQbY!hSavkt4ha22B4U64t3cWdc8lJAX9ul0ITVM0qssAGuE

**Comment by Calinou** [comment]
> From help and after reading source code (because 'help' is out of date):

Please report this on https://github.com/shssoichiro/oxipng/issues :slightly_smiling_face:

**Pull request closed without merging**
