### PR TITLE
Adding "Classic" fonts

### PR DESCRIPTION
**Pull request by MuadDib90**
I am trying to add 5 font characters to Classic folder.
This is primary for my educational purposes, so I know, what to do in the future.
I copied existing files from Classic font folder, adjusted them in paint.NET, and then saved as another files with the name hinted in the console using "netevent testuifont"
@Talon1024 can you please check, if I did everything right?

### CODE REVIEW

**Comment by Username-N00b-is-not-available** [comment]
@MuadDib90 Does your addition work ingame? Have you added offsets to letters (e. g. through SLADE)?

**Comment by Tormentor667** [comment]
The glyphs at least look very good to me :)

**Comment by MuadDib90** [comment]
> 
> 
> @MuadDib90 Does your addition work ingame? Have you added offsets to letters (e. g. through SLADE)?

Well, I don't know, if they work ingame, since they should be "unused" ones. So how can I try them?
About the offsets, no. I kindly asked @Talon1024 on FB chat to explain me, what to do exactly with fonts in SLADE, I have really no idea, how to work with it.
What I did, was copy an existing font PNG, rename it to proper hex number, edit it and then save.

**Comment by Talon1024** [comment]
In SLADE, when viewing images, you can set the offset mode to "Sprite". Then, look at the offsets of the other font character images, especially the ones which your new font characters are based on. Then, set the offsets so that the character doesn't look weirdly positioned in comparison to the others.

Since the "Classic" font doesn't have offsets, you really only need offsets if you have to change the vertical position of the character, or if you add space above the character image.

**Comment by Talon1024** [comment]
Screenshot_Doom_20210130_192558
P.S. This is what (some of) these new font characters look like ingame.

**Comment by MuadDib90** [comment]
> 
> 
> Screenshot_Doom_20210130_192558
> P.S. This is what (some of) these new font characters look like ingame.

How could you use that font in TES_DLG? I don't have it in the menu as a choosable option... Why?

And as fot this (at least) Classical font, I don't have to do (adjust, add) anything other than (if I understand it correctly):
- Edit some existing / create new one font character
- Save it as a new one with proper hex name
- Put it in the proper folder
- Check it myself ingame if it looks as it should
- Pull request so senior members can check my work

(Are there any other fonts, which behave as this one? So I can start with these "easier ones"?)

**Comment by Talon1024** [comment]
> (Are there any other fonts, which behave as this one? So I can start with these "easier ones"?)

Maybe BIGFONT, but BIGFONT characters with diacritics above them may need offsets, especially capital letters. You could also try one of the monospace fonts, but that will most likely require editing an existing sheet.

**Comment by MuadDib90** [comment]
And why I can't select some of the fonts (including Classic), when testing papertexts in TEST_DLG please?

**Comment by Talon1024** [comment]
You can; "Classic" has replaced "run14" in the font selector for text papers. I just haven't updated TEST_DLG to reflect that change.

**Comment by MuadDib90** [comment]
Soo, are those 5 characters from this request OK, or will they need some adjustments?
Did someone checked them please?
@Talon1024 @Username-N00b-is-not-available @Tormentor667

**Comment by Tormentor667** [comment]
Well, we can merge the pull request and you can try it on your own - or at least try it on your local build. If the offsets are there and the characters work in a full text, I am okay with them :)

**Comment by MuadDib90** [comment]
I am waiting to @Talon1024's commit, where he update the TEST_DLG, so I can try it myself.
But I think it should be fine, because I copied them from existing ones.
Also did the rest of the Classic font; waiting to be uploaded, after we confirm this to be without problems.

**Comment by Ozymandias81** [comment]
Just merged, let us know if everything works then as intended :)

**Pull request merged**
