### PR TITLE
Improve INTERMAP multiplayer support

### PR DESCRIPTION
**Pull request by yqco**
- Extend map's script support to theoretically any number of players (up from 4 or 1 in some cases)
- Make level exit logic apply to all players (not just activating player)
- Execute the level exit logic no matter how the level is exited
- Fix training area removing grenades from all players rather than just players inside training area
- Handle case where players are still in training area when level changes
- Remove training weapon pickups when lessons end (to counteract weapon stay in multiplayer)
- Purchased grenades are always seized/returned when entering/leaving training area
- Make training grenades undroppable
- Improve visual and audio feedback for grenade and rocket caches
- Disable grenade and rocket cache when lesson ends
- Restrict grenade "stupid" message to local player
- Make players always in Buddha mode while on INTERMAP (to prevent death from training grenades/rockets or fall damage)

Full diff can be seen [here](https://github.com/yqco/WolfenDoom/commit/719a5fb17ccd6016c62e7f8c3bb9b5aa8c04bb56). I changed Buddha to always be on since players can die from things other than the mines. Not sure if that's okay or not.

The grenade stashing logic for the training area used to be all over the place. Now it's limited to the entrance and exit of the training area (and at level exit):
Grenade stashing/returning at training entrance
Same thing happens at training area exit.

### CODE REVIEW

**Comment by Tormentor667** [comment]
Thanks alot for these! 

Did you already take the C1M6-railshooter script into account?

**Comment by yqco** [comment]
I haven't but I'll take a look at it now. Is there anything wrong with it in particular?

**Comment by Tormentor667** [comment]
I can't try multiplayer on my own unfortunately. By the way, the movement of the cart doesn't seem perfect as well, what do you think?

**Comment by yqco** [comment]
Some places feel a bit "floaty." I think the pitch might be interpolated too slowly.

**Comment by Tormentor667** [comment]
Do you think you can improve that?

**Comment by yqco** [comment]
I've made a [pull request](https://github.com/Realm667/WolfenDoom/pull/48) that hopefully improves the issue. See before and after comparisons [here](https://streamable.com/updj).

The cart still drifts horizontally off the track but now it stays grounded the entire time. Tweaking the interpolation points might reduce the drift issue.

**Pull request merged**
