### PR TITLE
First PR: skills, ENDOOM, new NPC

### PR DESCRIPTION
**Pull request by Username-N00b-is-not-available**
Added skill and episode names to language.csv (changed them to English translations; are these legacy from ww-nazis?); STARTUP.DAT-like ENDOOM; sprite and new messages (CSV diff lines 1542--1567) are for a secret sidequest NPC for C3M5_A I am currently working on.

### CODE REVIEW

**Comment by Ozymandias81** [comment]
Nice PR and happy that you finally manage to get this sorted @Username-N00b-is-not-available . I like the ENDOOM screen and most of the changes done here, but we of BoA team need to discuss more about the mildy game changer planned from you for the sidequest and, I guess it is you, changes that will be added already mentioned at First point of issue #178 
Will wait for @Tormentor667 to understand if this needs to be merged fully or that something must be cherry picked.

**Comment by Username-N00b-is-not-available** [comment]
Thank you!
Yes, all of that anonymous feedback was from me (as were 95% of translated lines).
I would like to place this NPC independently of the spies into the initial area of C3M5_A (sewers), into some kind of a secret passage from some entry point like these:
temp
(the underwater one would be better as no overused grate trope would be there involved :-) )
Concerning skill names: what do you personally think about the translation of them into English? Is it appropriate or not? It may look like that I am looking at them like at just another text strings to translate — indeed, 'if all you have is a hammer, everything looks like a nail' :-) But, for instance, original Wolfenstein 3-D did not have its skill names written in German, and neither did WolfenDoom by Laz Rojas.

**Comment by Username-N00b-is-not-available** [comment]
Thank you!

**Comment by Tormentor667** [comment]
What is the sprite supposed to be?

**Pull request merged**
