### PR TITLE
ZScriptified screen overlays

### PR DESCRIPTION
**Pull request by AFADoomer**
- Generalized the implementation of screen overlays and underlays to let the drawing be initiated from actors.
- Converted heartbeat ACS to an inventory actor that is given/taken based on the existing HealthScriptDeactivate global variable in ACS
- Updated PowerFactor, PowerSlow, PowerZyklonMask, and PowerSpaceSuit to initialize and update their own overlay information
- Removed player class call to ACS overlay wrapper, and removed relevant ACS code that was replaced

Publishing this as a pull request in case we want to wait to see if a bugfix minor point release is necessary before 3.1.

### CODE REVIEW

**Comment by Ozymandias81** [comment]
While I didn't check the whole commit, could it improve this somehow? #556

**Comment by Talon1024** [comment]
> While I didn't check the whole commit, could it improve this somehow? #556

Those are hardware-specific issues with the shaders, and I don't think this will have any effect on the shader issues.

**Comment by AFADoomer** [comment]
Yeah, this doesn't do anything with the screen shaders.

**Comment by Tormentor667** [comment]
If you ask me, we can merge the request, most of BoA seems to work fine and we can now take our time and concentrate on 3.1

**Pull request merged**
