### PR TITLE
C1M4 New non-grey doors

### PR DESCRIPTION
**Pull request by davidxn**
Every door in C1M4 is dark grey! Added a new door DOOR_B98 to indicate they're openable, was trying for a subtly aquatic colour with very dirty glass. If not this one, DOOR_B91 would work equally well

### CODE REVIEW

**Comment by davidxn** [comment]
It occurs to me that having two pull requests on the same map (the other being https://github.com/Realm667/WolfenDoom/pull/244 ) risk overwriting each other as they're seen as binary files, unless Git is spectacular about identifying changes - how does the team usually handle this?

**Comment by AFADoomer** [comment]
Most of the team are direct contributors, so I don't think it's been an issue before...  

In this case, at least, I'd recommend just making a single pull request with both sets of changes.  If Torm decides he doesn't want the door texture changes for whatever reason, we can easily make the friendly flag changes in master directly.

**Comment by Tormentor667** [comment]
The problem now is that I merged the fix with the friendly npcs already and this one now conflicts with the previous merge. Can you just re-commit this pull request @davidxn ?

**Comment by Ozymandias81** [comment]
I am going to cherry-pick changes here and apply to C1M4, so I'll close this.

**Comment by davidxn** [comment]
Thanks! I’ll do that :)

**Pull request closed without merging**
